name: Test
on: [push, workflow_dispatch]
env:
   SCHEME_NAME: 'EhPanda'
   DEVELOPER_DIR: /Applications/Xcode_15.4.app
jobs:
  Test:
    runs-on: macos-14
    if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Run tests
        run: xcodebuild clean test
          -skipMacroValidation
          -sdk iphonesimulator
          -scheme ${{ env.SCHEME_NAME }}
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro'
